name: Run Tests

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.4'

      - name: Install dependencies
        run: |
          pip install -e .

      - name: Run tests
        run: |
          python tests/AStar_planner_test.py
          python tests/DStar_Lite_planner_test.py
          python tests/DWA_planner_test.py
          python tests/kinematics_test.py
          python tests/lidar_mock_test.py
          python tests/path_planner_test.py
          python tests/pure_pursuit_test.py
          python tests/state_machine_test.py
          python tests/waypoint_nav_test.py