name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: Windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14.4'

      - name: Install dependencies
        run: |
          pip install -e .

      - name: Run tests
        run: |
          python tests/AStar_planner_test.py tests/DStar_Lite_planner_test.py tests/DWA_planner_test.py tests/kinematics_test.py tests/lidar_mock_test.py tests/path_planner_test.py tests/path_planner_test.py tests/pure_pursuit_tests.py tests/state_machine_test.py tests/waypoint_nav_test.py